### ISSUE TITLE
Robust deep reinforcement learning with adversarial attacks.

### ISSUE THREAD

**Issue by potatoKiller0** [huanzhang12/SA_PPO#1]
Hi, in your paper, you compare your result with 'Robust deep reinforcement learning with adversarial attacks.'. I can't find the code. Could you provide it,thanks.

**Comment by huanzhang12** [comment]
I implemented their algorithm but the code is not released in this repository. However, you can find an implementation of their algorithm in the new repository of my recent [ICLR paper](https://arxiv.org/pdf/2101.08452.pdf) on robust ATLA-PPO: https://github.com/huanzhang12/ATLA_robust_RL

Using the new code repository, you can run the following command (this uses the Ant environment as an example):
```bash
python run.py --config-path config_ant_vanilla_ppo.json --robust-ppo-eps 0.15 --attack-method critic --attack-ratio 1.0 --collect-perturbed-states true
```

`--robust-ppo-eps` specifies the epsilon for training time adversarial attack; `--attack-method` is the attack algorithm for training time attack (default is the `critic` attack; see [here](https://github.com/huanzhang12/ATLA_robust_RL#agent-evaluation-under-attacks) for a list of attacks; for example, you can also try our MAD attack); `--attack-ratio` specifies the percentage of states under attack (you can try 0.5 and 1.0; sometimes 1.0 leads to divergence). `--collect-perturbed-states true` means collecting the trajectory using the perturbed observations (rather than the ground-truth states) during training; I found that it is important for their algorithm to converge.

**Comment by potatoKiller0** [comment]
Thanks.
